#docker compose -f docker-compose.test.yml up --build

version: '3'

services:
  app:
    image: 'frm-boilerplate'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_ENV: 'docker-test'
    environment:
      APP_ENV: 'docker-test'
    command: ["/bin/sh", "-c", "PYTHONPATH=/app /home/appuser/.local/share/virtualenvs/app-4PlAip0Q/bin/pytest tests/modules/comment/"] # modified to run tests only for comment module
    depends_on:
      app-db:
        condition: service_started
      temporal:
        condition: service_healthy
    volumes:
      - ./output:/app/output

  app-db:
    image: mongo:5.0
    command: mongod --quiet --logpath /dev/null
    ports:
      - '27017:27017'

  temporal:
    image: temporalio/auto-setup:1.27.0
    depends_on:
      - temporal-db
    environment:
      DB: 'postgres12'
      DB_PORT: '5432'
      POSTGRES_USER: 'temporal'
      POSTGRES_PWD: 'temporal'
      POSTGRES_SEEDS: 'temporal-db'
      DYNAMIC_CONFIG_FILE_PATH: 'config/temporal-sql.yaml'
    healthcheck:
      test:
        [
          "CMD",
          "tctl",
          "--address",
          "temporal:7233",
          "workflow",
          "list"
        ]
      interval: 1s
      timeout: 5s
      retries: 30
    ports:
      - '7233:7233'
    volumes:
      - './temporal-sql.yaml:/etc/temporal/config/temporal-sql.yaml'

  temporal-db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: 'temporal'
      POSTGRES_USER: 'temporal'
    ports:
      - '5432:5432'
